server:
  port: 8091

spring:
  application:
    name: seckill-service
  redis:
    host: 192.168.1.135
  datasource:
    url: jdbc:mysql:///hm49?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.135:9300
  jackson:
    default-property-inclusion: non_null #配置json处理时忽略空值
  rabbitmq:
    host: 192.168.1.135
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ORDER.EXCHANGE#设置交换机


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    #instance-id: ${spring.application.name}:${server.port}
    #prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    #ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

leyou:
  jwt:
    pubKeyPath: F:\\学业资料\\java\\Java项目\\乐优商城\\temp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称






#通过feignclient调用订单服务下订单，可能出现超时的情况，需要配置下ribbon和hystrix
ribbon:
  ConnectTimeout: 400 #连接时间超时（ms）
  ReadTimeout: 200 #通信时间超时（ms）
  OkToRetryOnAllOperations: true #是否对所有操作重试
  MaxAutoRetriesNextServer: 1 #对同一服务不同实例的重试次数
  MaxAutoRetries: 1 #同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 #熔断超时时长：10000ms
