server:
  port: 8090

spring:
  application:
    name: cart-service
  redis:
    host: 192.168.1.135


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

leyou:
  jwt:
    pubKeyPath: F:\学业资料\java\Java项目\乐优商城\temp\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
